export default defineEventHandler((event) => {
  return {
    name: 'Creme Facial',
    brand: 'Naturale',
    originalPrice: 59.99,
    actualPrice: 35.99,
    availableQtd: 20,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a ultricies velit. Etiam vel pulvinar dolor. Mauris maximus ac arcu vitae mollis. Nulla at nisl vestibulum, malesuada mi id, tincidunt leo. Morbi congue volutpat purus, eu ullamcorper est blandit id. Vivamus egestas facilisis scelerisque. Proin non lorem risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent rutrum commodo porta. \n Integer id finibus orci. Maecenas porttitor lacinia laoreet. Donec faucibus erat sapien, quis laoreet elit hendrerit sit amet. Donec id quam orci. Pellentesque pretium venenatis interdum. Mauris quis dui ligula. Curabitur volutpat accumsan mauris, eget gravida nulla laoreet a. Nullam vitae felis pharetra, ultricies dolor eu, scelerisque massa. Sed vehicula justo sed fermentum interdum. Maecenas porta, quam interdum ornare maximus, nisi eros hendrerit felis, quis dictum urna purus accumsan massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tempor bibendum dolor, hendrerit pellentesque ipsum accumsan et. Quisque sollicitudin mi sed lacus tincidunt fringilla. Cras lobortis tellus vel laoreet feugiat. Suspendisse ullamcorper diam eu erat venenatis, ac egestas urna tempor. Suspendisse mollis nunc a massa fermentum dignissim. Curabitur placerat ante eget est semper, sed accumsan ante ullamcorper. Proin aliquam ex dolor, in vulputate elit sagittis et. Mauris non est ligula. Nullam maximus dolor sollicitudin enim elementum mattis. Cras suscipit luctus ligula ac pretium. Quisque libero purus, vestibulum a justo vitae, tincidunt varius nunc. \n Maecenas a sapien mattis nulla pharetra efficitur non a nisl. Fusce in venenatis odio, et ornare libero. Ut pharetra, felis vitae accumsan volutpat, magna magna facilisis est, vitae sollicitudin dolor erat ut mauris. Maecenas luctus tempus risus, ac porta purus lacinia et. Suspendisse egestas laoreet erat, at iaculis purus viverra ornare. Fusce ut tellus lacinia, auctor odio vitae, tempus arcu. Curabitur tempor lacus eget mi semper, sed ultricies erat placerat. Nullam non dolor at libero volutpat semper. Morbi imperdiet augue ut vehicula pellentesque. Quisque tincidunt venenatis lacinia. Phasellus quis porttitor mauris, eu tempus quam. Suspendisse gravida turpis nibh, eu malesuada dolor eleifend id.',
    images: [
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fthefiftypluslife.com%2Fwp-content%2Fuploads%2F2017%2F03%2F08-worst-advice-dermatologists-moisturizer.jpg&f=1&nofb=1&ipt=c78a2a57185846da214f2cd4212a1f907e62c783600be101293dba0c07a20ddd&ipo=images',
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2F1.bp.blogspot.com%2F-VcZKhznVauk%2FVRPajwrRN0I%2FAAAAAAAAAAg%2FF3yu0E9_Vbg%2Fs1600%2FBest%2BAnti%2BAging%2BNight%2BCream%2BSkinthera%2BRetinol.jpg&f=1&nofb=1&ipt=c24fbccd5e86a870429c2b31eeacfdbbdf2a9625de63364a1f8c42023c071202&ipo=images',
      'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.ctfassets.net%2Fpi28xy1s107o%2FLlm5Up8PUxQhf2ums4qZ0%2Fd17abadf962c30ceef96ebccd7d7631b%2FOur_Editor_s_Pre-Foundation_Secret_To_A_Flawless_Base_IT_Cosmetics_Confidence_In_A_Cream_0003.jpg&f=1&nofb=1&ipt=7c24140d060087bf08b9bd782cb84e184a75747df8bbf6ccb4034ae11d5e7c3d&ipo=images',
    ],
  };
});
